/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.seatecnologia.test.todolist.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaskList service. Represents a row in the &quot;TDL_TaskList&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link br.com.seatecnologia.test.todolist.model.impl.TaskListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link br.com.seatecnologia.test.todolist.model.impl.TaskListImpl}.
 * </p>
 *
 * @author Marcello Gurgel Sasaki
 * @see TaskList
 * @see br.com.seatecnologia.test.todolist.model.impl.TaskListImpl
 * @see br.com.seatecnologia.test.todolist.model.impl.TaskListModelImpl
 * @generated
 */
public interface TaskListModel extends BaseModel<TaskList>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task list model instance should use the {@link TaskList} interface instead.
	 */

	/**
	 * Returns the primary key of this task list.
	 *
	 * @return the primary key of this task list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task list.
	 *
	 * @param primaryKey the primary key of this task list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this task list.
	 *
	 * @return the uuid of this task list
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this task list.
	 *
	 * @param uuid the uuid of this task list
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the task list ID of this task list.
	 *
	 * @return the task list ID of this task list
	 */
	public long getTaskListId();

	/**
	 * Sets the task list ID of this task list.
	 *
	 * @param taskListId the task list ID of this task list
	 */
	public void setTaskListId(long taskListId);

	/**
	 * Returns the group ID of this task list.
	 *
	 * @return the group ID of this task list
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task list.
	 *
	 * @param groupId the group ID of this task list
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task list.
	 *
	 * @return the company ID of this task list
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task list.
	 *
	 * @param companyId the company ID of this task list
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this task list.
	 *
	 * @return the user ID of this task list
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task list.
	 *
	 * @param userId the user ID of this task list
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task list.
	 *
	 * @return the user uuid of this task list
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this task list.
	 *
	 * @param userUuid the user uuid of this task list
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task list.
	 *
	 * @return the user name of this task list
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task list.
	 *
	 * @param userName the user name of this task list
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task list.
	 *
	 * @return the create date of this task list
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task list.
	 *
	 * @param createDate the create date of this task list
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task list.
	 *
	 * @return the modified date of this task list
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task list.
	 *
	 * @param modifiedDate the modified date of this task list
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this task list.
	 *
	 * @return the name of this task list
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this task list.
	 *
	 * @param name the name of this task list
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		br.com.seatecnologia.test.todolist.model.TaskList taskList);

	@Override
	public int hashCode();

	@Override
	public CacheModel<br.com.seatecnologia.test.todolist.model.TaskList> toCacheModel();

	@Override
	public br.com.seatecnologia.test.todolist.model.TaskList toEscapedModel();

	@Override
	public br.com.seatecnologia.test.todolist.model.TaskList toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}